using System;
using System.Collections.Frozen;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using MegaCrit.Sts2.Core.Models.Powers;

namespace STS2.Agent.Sim;

/// <summary>
/// Static <c>Type â†’ SimPowerType</c> lookup table. Built once by the type
/// initializer and frozen for read-only access. <see cref="FrozenDictionary{TKey,TValue}"/>
/// picks an optimal hash layout at construction time, giving 2-4x faster reads
/// than the regular Dictionary on reference-type keys â€” exactly what FromReal
/// needs in the MCTS hot path.
///
/// If the game adds, removes, or renames a PowerModel subclass, this dictionary
/// fails to compile (broken <c>typeof()</c>) â€” exactly the breakage we want, so
/// missing powers cannot silently slip into FromReal.
/// </summary>
internal static class SimPowerRegistry
{
    private static readonly FrozenDictionary<Type, int> _byType =
        new Dictionary<Type, int>(SimPowerType.Count)
        {
            { typeof(AccelerantPower), SimPowerType.Accelerant },
            { typeof(AccuracyPower), SimPowerType.Accuracy },
            { typeof(AdaptablePower), SimPowerType.Adaptable },
            { typeof(AfterimagePower), SimPowerType.Afterimage },
            { typeof(AggressionPower), SimPowerType.Aggression },
            { typeof(AnticipatePower), SimPowerType.Anticipate },
            { typeof(ArsenalPower), SimPowerType.Arsenal },
            { typeof(ArtifactPower), SimPowerType.Artifact },
            { typeof(AsleepPower), SimPowerType.Asleep },
            { typeof(AutomationPower), SimPowerType.Automation },
            { typeof(BackAttackLeftPower), SimPowerType.BackAttackLeft },
            { typeof(BackAttackRightPower), SimPowerType.BackAttackRight },
            { typeof(BarricadePower), SimPowerType.Barricade },
            { typeof(BattlewornDummyTimeLimitPower), SimPowerType.BattlewornDummyTimeLimit },
            { typeof(BeaconOfHopePower), SimPowerType.BeaconOfHope },
            { typeof(BiasedCognitionPower), SimPowerType.BiasedCognition },
            { typeof(BlackHolePower), SimPowerType.BlackHole },
            { typeof(BlockNextTurnPower), SimPowerType.BlockNextTurn },
            { typeof(BlurPower), SimPowerType.Blur },
            { typeof(BorrowedTimePower), SimPowerType.BorrowedTime },
            { typeof(BufferPower), SimPowerType.Buffer },
            { typeof(BurrowedPower), SimPowerType.Burrowed },
            { typeof(BurstPower), SimPowerType.Burst },
            { typeof(CalamityPower), SimPowerType.Calamity },
            { typeof(CalcifyPower), SimPowerType.Calcify },
            { typeof(CallOfTheVoidPower), SimPowerType.CallOfTheVoid },
            { typeof(ChainsOfBindingPower), SimPowerType.ChainsOfBinding },
            { typeof(ChildOfTheStarsPower), SimPowerType.ChildOfTheStars },
            { typeof(ClarityPower), SimPowerType.Clarity },
            { typeof(ColossusPower), SimPowerType.Colossus },
            { typeof(ConfusedPower), SimPowerType.Confused },
            { typeof(ConquerorPower), SimPowerType.Conqueror },
            { typeof(ConstrictPower), SimPowerType.Constrict },
            { typeof(ConsumingShadowPower), SimPowerType.ConsumingShadow },
            { typeof(CoolantPower), SimPowerType.Coolant },
            { typeof(CoordinatePower), SimPowerType.Coordinate },
            { typeof(CorrosiveWavePower), SimPowerType.CorrosiveWave },
            { typeof(CorruptionPower), SimPowerType.Corruption },
            { typeof(CountdownPower), SimPowerType.Countdown },
            { typeof(CoveredPower), SimPowerType.Covered },
            { typeof(CrabRagePower), SimPowerType.CrabRage },
            { typeof(CreativeAiPower), SimPowerType.CreativeAi },
            { typeof(CrimsonMantlePower), SimPowerType.CrimsonMantle },
            { typeof(CrueltyPower), SimPowerType.Cruelty },
            { typeof(CrushUnderPower), SimPowerType.CrushUnder },
            { typeof(CuriousPower), SimPowerType.Curious },
            { typeof(CurlUpPower), SimPowerType.CurlUp },
            { typeof(DampenPower), SimPowerType.Dampen },
            { typeof(DanseMacabrePower), SimPowerType.DanseMacabre },
            { typeof(DarkEmbracePower), SimPowerType.DarkEmbrace },
            { typeof(DarkShacklesPower), SimPowerType.DarkShackles },
            { typeof(DebilitatePower), SimPowerType.Debilitate },
            { typeof(DemesnePower), SimPowerType.Demesne },
            { typeof(DemisePower), SimPowerType.Demise },
            { typeof(DemonFormPower), SimPowerType.DemonForm },
            { typeof(DevourLifePower), SimPowerType.DevourLife },
            { typeof(DexterityPower), SimPowerType.Dexterity },
            { typeof(DiamondDiademPower), SimPowerType.DiamondDiadem },
            { typeof(DieForYouPower), SimPowerType.DieForYou },
            { typeof(DisintegrationPower), SimPowerType.Disintegration },
            { typeof(DoomPower), SimPowerType.Doom },
            { typeof(DoubleDamagePower), SimPowerType.DoubleDamage },
            { typeof(DrawCardsNextTurnPower), SimPowerType.DrawCardsNextTurn },
            { typeof(DrumOfBattlePower), SimPowerType.DrumOfBattle },
            { typeof(DuplicationPower), SimPowerType.Duplication },
            { typeof(DyingStarPower), SimPowerType.DyingStar },
            { typeof(EchoFormPower), SimPowerType.EchoForm },
            { typeof(EnergyNextTurnPower), SimPowerType.EnergyNextTurn },
            { typeof(EnfeeblingTouchPower), SimPowerType.EnfeeblingTouch },
            { typeof(EnragePower), SimPowerType.Enrage },
            { typeof(EntropyPower), SimPowerType.Entropy },
            { typeof(EnvenomPower), SimPowerType.Envenom },
            { typeof(EscapeArtistPower), SimPowerType.EscapeArtist },
            { typeof(FanOfKnivesPower), SimPowerType.FanOfKnives },
            { typeof(FastenPower), SimPowerType.Fasten },
            { typeof(FeedingFrenzyPower), SimPowerType.FeedingFrenzy },
            { typeof(FeelNoPainPower), SimPowerType.FeelNoPain },
            { typeof(FeralPower), SimPowerType.Feral },
            { typeof(FlameBarrierPower), SimPowerType.FlameBarrier },
            { typeof(FlankingPower), SimPowerType.Flanking },
            { typeof(FlexPotionPower), SimPowerType.FlexPotion },
            { typeof(FlutterPower), SimPowerType.Flutter },
            { typeof(FocusedStrikePower), SimPowerType.FocusedStrike },
            { typeof(FocusPower), SimPowerType.Focus },
            { typeof(ForbiddenGrimoirePower), SimPowerType.ForbiddenGrimoire },
            { typeof(ForegoneConclusionPower), SimPowerType.ForegoneConclusion },
            { typeof(FrailPower), SimPowerType.Frail },
            { typeof(FreeAttackPower), SimPowerType.FreeAttack },
            { typeof(FreePowerPower), SimPowerType.FreePower },
            { typeof(FreeSkillPower), SimPowerType.FreeSkill },
            { typeof(FriendshipPower), SimPowerType.Friendship },
            { typeof(FurnacePower), SimPowerType.Furnace },
            { typeof(GalvanicPower), SimPowerType.Galvanic },
            { typeof(GenesisPower), SimPowerType.Genesis },
            { typeof(GigantificationPower), SimPowerType.Gigantification },
            { typeof(GraspPower), SimPowerType.Grasp },
            { typeof(GravityPower), SimPowerType.Gravity },
            { typeof(GuardedPower), SimPowerType.Guarded },
            { typeof(HailstormPower), SimPowerType.Hailstorm },
            { typeof(HammerTimePower), SimPowerType.HammerTime },
            { typeof(HangPower), SimPowerType.Hang },
            { typeof(HardenedShellPower), SimPowerType.HardenedShell },
            { typeof(HardToKillPower), SimPowerType.HardToKill },
            { typeof(HatchPower), SimPowerType.Hatch },
            { typeof(HauntPower), SimPowerType.Haunt },
            { typeof(HeistPower), SimPowerType.Heist },
            { typeof(HelicalDartPower), SimPowerType.HelicalDart },
            { typeof(HelloWorldPower), SimPowerType.HelloWorld },
            { typeof(HellraiserPower), SimPowerType.Hellraiser },
            { typeof(HexPower), SimPowerType.Hex },
            { typeof(HighVoltagePower), SimPowerType.HighVoltage },
            { typeof(HotfixPower), SimPowerType.Hotfix },
            { typeof(HungerPower), SimPowerType.Hunger },
            { typeof(IllusionPower), SimPowerType.Illusion },
            { typeof(ImbalancedPower), SimPowerType.Imbalanced },
            { typeof(ImprovementPower), SimPowerType.Improvement },
            { typeof(InfernoPower), SimPowerType.Inferno },
            { typeof(InfestedPower), SimPowerType.Infested },
            { typeof(InfiniteBladesPower), SimPowerType.InfiniteBlades },
            { typeof(IntangiblePower), SimPowerType.Intangible },
            { typeof(InterceptPower), SimPowerType.Intercept },
            { typeof(IterationPower), SimPowerType.Iteration },
            { typeof(JuggernautPower), SimPowerType.Juggernaut },
            { typeof(JugglingPower), SimPowerType.Juggling },
            { typeof(KnockdownPower), SimPowerType.Knockdown },
            { typeof(LeadershipPower), SimPowerType.Leadership },
            { typeof(LethalityPower), SimPowerType.Lethality },
            { typeof(LightningRodPower), SimPowerType.LightningRod },
            { typeof(LoopPower), SimPowerType.Loop },
            { typeof(MachineLearningPower), SimPowerType.MachineLearning },
            { typeof(MagicBombPower), SimPowerType.MagicBomb },
            { typeof(ManglePower), SimPowerType.Mangle },
            { typeof(MasterPlannerPower), SimPowerType.MasterPlanner },
            { typeof(MayhemPower), SimPowerType.Mayhem },
            { typeof(MindRotPower), SimPowerType.MindRot },
            { typeof(MinionPower), SimPowerType.Minion },
            { typeof(MonarchsGazePower), SimPowerType.MonarchsGaze },
            { typeof(MonarchsGazeStrengthDownPower), SimPowerType.MonarchsGazeStrengthDown },
            { typeof(MonologuePower), SimPowerType.Monologue },
            { typeof(NecroMasteryPower), SimPowerType.NecroMastery },
            { typeof(NemesisPower), SimPowerType.Nemesis },
            { typeof(NeurosurgePower), SimPowerType.Neurosurge },
            { typeof(NightmarePower), SimPowerType.Nightmare },
            { typeof(NoBlockPower), SimPowerType.NoBlock },
            { typeof(NoDrawPower), SimPowerType.NoDraw },
            { typeof(NoEnergyGainPower), SimPowerType.NoEnergyGain },
            { typeof(NostalgiaPower), SimPowerType.Nostalgia },
            { typeof(NoxiousFumesPower), SimPowerType.NoxiousFumes },
            { typeof(OblivionPower), SimPowerType.Oblivion },
            { typeof(OneTwoPunchPower), SimPowerType.OneTwoPunch },
            { typeof(OrbitPower), SimPowerType.Orbit },
            { typeof(OutbreakPower), SimPowerType.Outbreak },
            { typeof(PagestormPower), SimPowerType.Pagestorm },
            { typeof(PainfulStabsPower), SimPowerType.PainfulStabs },
            { typeof(PaleBlueDotPower), SimPowerType.PaleBlueDot },
            { typeof(PanachePower), SimPowerType.Panache },
            { typeof(PaperCutsPower), SimPowerType.PaperCuts },
            { typeof(ParryPower), SimPowerType.Parry },
            { typeof(PersonalHivePower), SimPowerType.PersonalHive },
            { typeof(PhantomBladesPower), SimPowerType.PhantomBlades },
            { typeof(PiercingWailPower), SimPowerType.PiercingWail },
            { typeof(PillarOfCreationPower), SimPowerType.PillarOfCreation },
            { typeof(PlatingPower), SimPowerType.Plating },
            { typeof(PlowPower), SimPowerType.Plow },
            { typeof(PoisonPower), SimPowerType.Poison },
            { typeof(PossessSpeedPower), SimPowerType.PossessSpeed },
            { typeof(PossessStrengthPower), SimPowerType.PossessStrength },
            { typeof(PrepTimePower), SimPowerType.PrepTime },
            { typeof(PyrePower), SimPowerType.Pyre },
            { typeof(RadiancePower), SimPowerType.Radiance },
            { typeof(RagePower), SimPowerType.Rage },
            { typeof(RampartPower), SimPowerType.Rampart },
            { typeof(RavenousPower), SimPowerType.Ravenous },
            { typeof(ReaperFormPower), SimPowerType.ReaperForm },
            { typeof(ReattachPower), SimPowerType.Reattach },
            { typeof(ReboundPower), SimPowerType.Rebound },
            { typeof(ReflectPower), SimPowerType.Reflect },
            { typeof(RegenPower), SimPowerType.Regen },
            { typeof(ReptileTrinketPower), SimPowerType.ReptileTrinket },
            { typeof(RetainHandPower), SimPowerType.RetainHand },
            { typeof(RingingPower), SimPowerType.Ringing },
            { typeof(RitualPower), SimPowerType.Ritual },
            { typeof(RollingBoulderPower), SimPowerType.RollingBoulder },
            { typeof(RoyaltiesPower), SimPowerType.Royalties },
            { typeof(RupturePower), SimPowerType.Rupture },
            { typeof(SandpitPower), SimPowerType.Sandpit },
            { typeof(ScrutinyPower), SimPowerType.Scrutiny },
            { typeof(SeekingEdgePower), SimPowerType.SeekingEdge },
            { typeof(SelfFormingClayPower), SimPowerType.SelfFormingClay },
            { typeof(SentryModePower), SimPowerType.SentryMode },
            { typeof(SerpentFormPower), SimPowerType.SerpentForm },
            { typeof(SetupStrikePower), SimPowerType.SetupStrike },
            { typeof(ShacklingPotionPower), SimPowerType.ShacklingPotion },
            { typeof(ShadowmeldPower), SimPowerType.Shadowmeld },
            { typeof(ShadowStepPower), SimPowerType.ShadowStep },
            { typeof(ShriekPower), SimPowerType.Shriek },
            { typeof(ShrinkPower), SimPowerType.Shrink },
            { typeof(ShroudPower), SimPowerType.Shroud },
            { typeof(SicEmPower), SimPowerType.SicEm },
            { typeof(SignalBoostPower), SimPowerType.SignalBoost },
            { typeof(SkittishPower), SimPowerType.Skittish },
            { typeof(SleightOfFleshPower), SimPowerType.SleightOfFlesh },
            { typeof(SlipperyPower), SimPowerType.Slippery },
            { typeof(SlothPower), SimPowerType.Sloth },
            { typeof(SlowPower), SimPowerType.Slow },
            { typeof(SlumberPower), SimPowerType.Slumber },
            { typeof(SmoggyPower), SimPowerType.Smoggy },
            { typeof(SmokestackPower), SimPowerType.Smokestack },
            { typeof(SneakyPower), SimPowerType.Sneaky },
            { typeof(SoarPower), SimPowerType.Soar },
            { typeof(SpectrumShiftPower), SimPowerType.SpectrumShift },
            { typeof(SpeedPotionPower), SimPowerType.SpeedPotion },
            { typeof(SpeedsterPower), SimPowerType.Speedster },
            { typeof(SpinnerPower), SimPowerType.Spinner },
            { typeof(SpiritOfAshPower), SimPowerType.SpiritOfAsh },
            { typeof(StampedePower), SimPowerType.Stampede },
            { typeof(StarNextTurnPower), SimPowerType.StarNextTurn },
            { typeof(SteamEruptionPower), SimPowerType.SteamEruption },
            { typeof(StockPower), SimPowerType.Stock },
            { typeof(StormPower), SimPowerType.Storm },
            { typeof(StranglePower), SimPowerType.Strangle },
            { typeof(StratagemPower), SimPowerType.Stratagem },
            { typeof(StrengthPower), SimPowerType.Strength },
            { typeof(SubroutinePower), SimPowerType.Subroutine },
            { typeof(SuckPower), SimPowerType.Suck },
            { typeof(SummonNextTurnPower), SimPowerType.SummonNextTurn },
            { typeof(SurprisePower), SimPowerType.Surprise },
            { typeof(SurroundedPower), SimPowerType.Surrounded },
            { typeof(SwipePower), SimPowerType.Swipe },
            { typeof(SwordSagePower), SimPowerType.SwordSage },
            { typeof(SynchronizePower), SimPowerType.Synchronize },
            { typeof(TagTeamPower), SimPowerType.TagTeam },
            { typeof(TangledPower), SimPowerType.Tangled },
            { typeof(TankPower), SimPowerType.Tank },
            { typeof(TenderPower), SimPowerType.Tender },
            { typeof(TerritorialPower), SimPowerType.Territorial },
            { typeof(TheBombPower), SimPowerType.TheBomb },
            { typeof(TheGambitPower), SimPowerType.TheGambit },
            { typeof(TheHuntPower), SimPowerType.TheHunt },
            { typeof(TheSealedThronePower), SimPowerType.TheSealedThrone },
            { typeof(ThieveryPower), SimPowerType.Thievery },
            { typeof(ThornsPower), SimPowerType.Thorns },
            { typeof(ThunderPower), SimPowerType.Thunder },
            { typeof(ToolsOfTheTradePower), SimPowerType.ToolsOfTheTrade },
            { typeof(ToricToughnessPower), SimPowerType.ToricToughness },
            { typeof(TrackingPower), SimPowerType.Tracking },
            { typeof(TrashToTreasurePower), SimPowerType.TrashToTreasure },
            { typeof(TyrannyPower), SimPowerType.Tyranny },
            { typeof(UnmovablePower), SimPowerType.Unmovable },
            { typeof(VeilpiercerPower), SimPowerType.Veilpiercer },
            { typeof(ViciousPower), SimPowerType.Vicious },
            { typeof(VigorPower), SimPowerType.Vigor },
            { typeof(VitalSparkPower), SimPowerType.VitalSpark },
            { typeof(VoidFormPower), SimPowerType.VoidForm },
            { typeof(VulnerablePower), SimPowerType.Vulnerable },
            { typeof(WasteAwayPower), SimPowerType.WasteAway },
            { typeof(WeakPower), SimPowerType.Weak },
            { typeof(WellLaidPlansPower), SimPowerType.WellLaidPlans },
            { typeof(WraithFormPower), SimPowerType.WraithForm },
        }.ToFrozenDictionary();

    /// <summary>
    /// Returns true if <paramref name="powerType"/> is a known PowerModel subclass.
    /// Use this in FromReal where unknown powers should be silently skipped (mod
    /// resilience: a future patch may ship powers our build doesn't know about).
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool TryGetIndex(Type powerType, out int index)
        => _byType.TryGetValue(powerType, out index);

    /// <summary>
    /// Returns the index, or throws if <paramref name="powerType"/> is unknown.
    /// Use where a missing entry means a build-time bug, not game-data drift.
    /// </summary>
    public static int GetIndex(Type powerType)
        => _byType.TryGetValue(powerType, out int idx)
            ? idx
            : throw new InvalidOperationException(
                $"SimPowerRegistry: unknown PowerModel subclass '{powerType.FullName}'. " +
                "Add it to SimPowerType and SimPowerRegistry.");
}
