using System;
using System.Collections.Frozen;
using System.Collections.Generic;
using System.Reflection;
using MegaCrit.Sts2.Core.Models;
using MegaCrit.Sts2.Core.Models.Relics;

namespace STS2.Agent.Sim;

/// <summary>
/// Static <c>Type -&gt; SimRelicId</c> lookup table, built the same way as <c>SimCardDb</c>. Also
/// classifies each relic as "counter-bearing" or not -- i.e. whether it overrides
/// <see cref="RelicModel.DisplayAmount"/> or <see cref="RelicModel.ShowCounter"/> beyond the base
/// class's always-0/always-false defaults. Unlike the Power/Enchantment/Affliction registries, this
/// classification does not need a hand-maintained table: it is derived once via reflection at
/// class-init time, since it only depends on each relic <em>type</em> (not on live game content
/// being loaded), so it can run eagerly instead of the lazy ModelDb-dependent pattern used by
/// <c>SimPotionRegistry</c> / <c>SimMonsterStateRegistry</c>.
///
/// Why this classification matters: relic identity (which relics a player holds) never changes
/// during a single combat (every AddRelicInternal/RemoveRelicInternal/MeltRelicInternal call site
/// in game_source is outside combat scope), so it is stored once per combat in
/// <see cref="CombatRootRelics"/> and shared by reference across every search node instead of being
/// re-copied per node. Only the ~13% of relics that actually carry a per-combat counter (Kunai,
/// Pen Nib, Nunchaku, etc.) need a slot in the small per-node counter array
/// (<see cref="CombatNodeBlob.RelicCounters"/>) -- the other ~87% are pure static stat modifiers
/// with nothing to track turn to turn.
/// </summary>
internal static class SimRelicDb
{
    private static readonly FrozenDictionary<Type, ushort> _byType =
        new Dictionary<Type, ushort>(SimRelicId.Count)
        {
            { typeof(Akabeko), SimRelicId.Akabeko },
            { typeof(AlchemicalCoffer), SimRelicId.AlchemicalCoffer },
            { typeof(AmethystAubergine), SimRelicId.AmethystAubergine },
            { typeof(Anchor), SimRelicId.Anchor },
            { typeof(ArcaneScroll), SimRelicId.ArcaneScroll },
            { typeof(ArchaicTooth), SimRelicId.ArchaicTooth },
            { typeof(ArtOfWar), SimRelicId.ArtOfWar },
            { typeof(Astrolabe), SimRelicId.Astrolabe },
            { typeof(BagOfMarbles), SimRelicId.BagOfMarbles },
            { typeof(BagOfPreparation), SimRelicId.BagOfPreparation },
            { typeof(BeatingRemnant), SimRelicId.BeatingRemnant },
            { typeof(BeautifulBracelet), SimRelicId.BeautifulBracelet },
            { typeof(Bellows), SimRelicId.Bellows },
            { typeof(BeltBuckle), SimRelicId.BeltBuckle },
            { typeof(BigHat), SimRelicId.BigHat },
            { typeof(BigMushroom), SimRelicId.BigMushroom },
            { typeof(BiiigHug), SimRelicId.BiiigHug },
            { typeof(BingBong), SimRelicId.BingBong },
            { typeof(BlackBlood), SimRelicId.BlackBlood },
            { typeof(BlackStar), SimRelicId.BlackStar },
            { typeof(BlessedAntler), SimRelicId.BlessedAntler },
            { typeof(BloodSoakedRose), SimRelicId.BloodSoakedRose },
            { typeof(BloodVial), SimRelicId.BloodVial },
            { typeof(BoneFlute), SimRelicId.BoneFlute },
            { typeof(BoneTea), SimRelicId.BoneTea },
            { typeof(Bookmark), SimRelicId.Bookmark },
            { typeof(BookOfFiveRings), SimRelicId.BookOfFiveRings },
            { typeof(BookRepairKnife), SimRelicId.BookRepairKnife },
            { typeof(BoomingConch), SimRelicId.BoomingConch },
            { typeof(BoundPhylactery), SimRelicId.BoundPhylactery },
            { typeof(BowlerHat), SimRelicId.BowlerHat },
            { typeof(Bread), SimRelicId.Bread },
            { typeof(BrilliantScarf), SimRelicId.BrilliantScarf },
            { typeof(Brimstone), SimRelicId.Brimstone },
            { typeof(BronzeScales), SimRelicId.BronzeScales },
            { typeof(BurningBlood), SimRelicId.BurningBlood },
            { typeof(BurningSticks), SimRelicId.BurningSticks },
            { typeof(Byrdpip), SimRelicId.Byrdpip },
            { typeof(CallingBell), SimRelicId.CallingBell },
            { typeof(Candelabra), SimRelicId.Candelabra },
            { typeof(CaptainsWheel), SimRelicId.CaptainsWheel },
            { typeof(Cauldron), SimRelicId.Cauldron },
            { typeof(CentennialPuzzle), SimRelicId.CentennialPuzzle },
            { typeof(Chandelier), SimRelicId.Chandelier },
            { typeof(CharonsAshes), SimRelicId.CharonsAshes },
            { typeof(ChemicalX), SimRelicId.ChemicalX },
            { typeof(ChoicesParadox), SimRelicId.ChoicesParadox },
            { typeof(ChosenCheese), SimRelicId.ChosenCheese },
            { typeof(Circlet), SimRelicId.Circlet },
            { typeof(Claws), SimRelicId.Claws },
            { typeof(CloakClasp), SimRelicId.CloakClasp },
            { typeof(CrackedCore), SimRelicId.CrackedCore },
            { typeof(Crossbow), SimRelicId.Crossbow },
            { typeof(CursedPearl), SimRelicId.CursedPearl },
            { typeof(DarkstonePeriapt), SimRelicId.DarkstonePeriapt },
            { typeof(DataDisk), SimRelicId.DataDisk },
            { typeof(DaughterOfTheWind), SimRelicId.DaughterOfTheWind },
            { typeof(DelicateFrond), SimRelicId.DelicateFrond },
            { typeof(DemonTongue), SimRelicId.DemonTongue },
            { typeof(DeprecatedRelic), SimRelicId.DeprecatedRelic },
            { typeof(DiamondDiadem), SimRelicId.DiamondDiadem },
            { typeof(DingyRug), SimRelicId.DingyRug },
            { typeof(DistinguishedCape), SimRelicId.DistinguishedCape },
            { typeof(DivineDestiny), SimRelicId.DivineDestiny },
            { typeof(DivineRight), SimRelicId.DivineRight },
            { typeof(DollysMirror), SimRelicId.DollysMirror },
            { typeof(DragonFruit), SimRelicId.DragonFruit },
            { typeof(DreamCatcher), SimRelicId.DreamCatcher },
            { typeof(Driftwood), SimRelicId.Driftwood },
            { typeof(DustyTome), SimRelicId.DustyTome },
            { typeof(Ectoplasm), SimRelicId.Ectoplasm },
            { typeof(ElectricShrymp), SimRelicId.ElectricShrymp },
            { typeof(EmberTea), SimRelicId.EmberTea },
            { typeof(EmotionChip), SimRelicId.EmotionChip },
            { typeof(EmptyCage), SimRelicId.EmptyCage },
            { typeof(EternalFeather), SimRelicId.EternalFeather },
            { typeof(FakeAnchor), SimRelicId.FakeAnchor },
            { typeof(FakeBloodVial), SimRelicId.FakeBloodVial },
            { typeof(FakeHappyFlower), SimRelicId.FakeHappyFlower },
            { typeof(FakeLeesWaffle), SimRelicId.FakeLeesWaffle },
            { typeof(FakeMango), SimRelicId.FakeMango },
            { typeof(FakeMerchantsRug), SimRelicId.FakeMerchantsRug },
            { typeof(FakeOrichalcum), SimRelicId.FakeOrichalcum },
            { typeof(FakeSneckoEye), SimRelicId.FakeSneckoEye },
            { typeof(FakeStrikeDummy), SimRelicId.FakeStrikeDummy },
            { typeof(FakeVenerableTeaSet), SimRelicId.FakeVenerableTeaSet },
            { typeof(FencingManual), SimRelicId.FencingManual },
            { typeof(FestivePopper), SimRelicId.FestivePopper },
            { typeof(Fiddle), SimRelicId.Fiddle },
            { typeof(FishingRod), SimRelicId.FishingRod },
            { typeof(ForgottenSoul), SimRelicId.ForgottenSoul },
            { typeof(FragrantMushroom), SimRelicId.FragrantMushroom },
            { typeof(FresnelLens), SimRelicId.FresnelLens },
            { typeof(FrozenEgg), SimRelicId.FrozenEgg },
            { typeof(FuneraryMask), SimRelicId.FuneraryMask },
            { typeof(FurCoat), SimRelicId.FurCoat },
            { typeof(GalacticDust), SimRelicId.GalacticDust },
            { typeof(GamblingChip), SimRelicId.GamblingChip },
            { typeof(GamePiece), SimRelicId.GamePiece },
            { typeof(GhostSeed), SimRelicId.GhostSeed },
            { typeof(Girya), SimRelicId.Girya },
            { typeof(GlassEye), SimRelicId.GlassEye },
            { typeof(Glitter), SimRelicId.Glitter },
            { typeof(GnarledHammer), SimRelicId.GnarledHammer },
            { typeof(GoldenCompass), SimRelicId.GoldenCompass },
            { typeof(GoldenPearl), SimRelicId.GoldenPearl },
            { typeof(GoldPlatedCables), SimRelicId.GoldPlatedCables },
            { typeof(Gorget), SimRelicId.Gorget },
            { typeof(GremlinHorn), SimRelicId.GremlinHorn },
            { typeof(HandDrill), SimRelicId.HandDrill },
            { typeof(HappyFlower), SimRelicId.HappyFlower },
            { typeof(HeftyTablet), SimRelicId.HeftyTablet },
            { typeof(HelicalDart), SimRelicId.HelicalDart },
            { typeof(HistoryCourse), SimRelicId.HistoryCourse },
            { typeof(HornCleat), SimRelicId.HornCleat },
            { typeof(IceCream), SimRelicId.IceCream },
            { typeof(InfusedCore), SimRelicId.InfusedCore },
            { typeof(IntimidatingHelmet), SimRelicId.IntimidatingHelmet },
            { typeof(IronClub), SimRelicId.IronClub },
            { typeof(IvoryTile), SimRelicId.IvoryTile },
            { typeof(JeweledMask), SimRelicId.JeweledMask },
            { typeof(JewelryBox), SimRelicId.JewelryBox },
            { typeof(JossPaper), SimRelicId.JossPaper },
            { typeof(JuzuBracelet), SimRelicId.JuzuBracelet },
            { typeof(Kaleidoscope), SimRelicId.Kaleidoscope },
            { typeof(Kifuda), SimRelicId.Kifuda },
            { typeof(Kunai), SimRelicId.Kunai },
            { typeof(Kusarigama), SimRelicId.Kusarigama },
            { typeof(Lantern), SimRelicId.Lantern },
            { typeof(LargeCapsule), SimRelicId.LargeCapsule },
            { typeof(LastingCandy), SimRelicId.LastingCandy },
            { typeof(LavaLamp), SimRelicId.LavaLamp },
            { typeof(LavaRock), SimRelicId.LavaRock },
            { typeof(LeadPaperweight), SimRelicId.LeadPaperweight },
            { typeof(LeafyPoultice), SimRelicId.LeafyPoultice },
            { typeof(LeesWaffle), SimRelicId.LeesWaffle },
            { typeof(LetterOpener), SimRelicId.LetterOpener },
            { typeof(LizardTail), SimRelicId.LizardTail },
            { typeof(LoomingFruit), SimRelicId.LoomingFruit },
            { typeof(LordsParasol), SimRelicId.LordsParasol },
            { typeof(LostCoffer), SimRelicId.LostCoffer },
            { typeof(LostWisp), SimRelicId.LostWisp },
            { typeof(LuckyFysh), SimRelicId.LuckyFysh },
            { typeof(LunarPastry), SimRelicId.LunarPastry },
            { typeof(Mango), SimRelicId.Mango },
            { typeof(MassiveScroll), SimRelicId.MassiveScroll },
            { typeof(MawBank), SimRelicId.MawBank },
            { typeof(MealTicket), SimRelicId.MealTicket },
            { typeof(MeatCleaver), SimRelicId.MeatCleaver },
            { typeof(MeatOnTheBone), SimRelicId.MeatOnTheBone },
            { typeof(MembershipCard), SimRelicId.MembershipCard },
            { typeof(MercuryHourglass), SimRelicId.MercuryHourglass },
            { typeof(Metronome), SimRelicId.Metronome },
            { typeof(MiniatureCannon), SimRelicId.MiniatureCannon },
            { typeof(MiniatureTent), SimRelicId.MiniatureTent },
            { typeof(MiniRegent), SimRelicId.MiniRegent },
            { typeof(MoltenEgg), SimRelicId.MoltenEgg },
            { typeof(MrStruggles), SimRelicId.MrStruggles },
            { typeof(MummifiedHand), SimRelicId.MummifiedHand },
            { typeof(MusicBox), SimRelicId.MusicBox },
            { typeof(MysticLighter), SimRelicId.MysticLighter },
            { typeof(NeowsBones), SimRelicId.NeowsBones },
            { typeof(NeowsTalisman), SimRelicId.NeowsTalisman },
            { typeof(NeowsTorment), SimRelicId.NeowsTorment },
            { typeof(NewLeaf), SimRelicId.NewLeaf },
            { typeof(NinjaScroll), SimRelicId.NinjaScroll },
            { typeof(Nunchaku), SimRelicId.Nunchaku },
            { typeof(NutritiousOyster), SimRelicId.NutritiousOyster },
            { typeof(NutritiousSoup), SimRelicId.NutritiousSoup },
            { typeof(OddlySmoothStone), SimRelicId.OddlySmoothStone },
            { typeof(OldCoin), SimRelicId.OldCoin },
            { typeof(OrangeDough), SimRelicId.OrangeDough },
            { typeof(Orichalcum), SimRelicId.Orichalcum },
            { typeof(OrnamentalFan), SimRelicId.OrnamentalFan },
            { typeof(Orrery), SimRelicId.Orrery },
            { typeof(PaelsBlood), SimRelicId.PaelsBlood },
            { typeof(PaelsClaw), SimRelicId.PaelsClaw },
            { typeof(PaelsEye), SimRelicId.PaelsEye },
            { typeof(PaelsFlesh), SimRelicId.PaelsFlesh },
            { typeof(PaelsGrowth), SimRelicId.PaelsGrowth },
            { typeof(PaelsHorn), SimRelicId.PaelsHorn },
            { typeof(PaelsLegion), SimRelicId.PaelsLegion },
            { typeof(PaelsTears), SimRelicId.PaelsTears },
            { typeof(PaelsTooth), SimRelicId.PaelsTooth },
            { typeof(PaelsWing), SimRelicId.PaelsWing },
            { typeof(PandorasBox), SimRelicId.PandorasBox },
            { typeof(Pantograph), SimRelicId.Pantograph },
            { typeof(PaperKrane), SimRelicId.PaperKrane },
            { typeof(PaperPhrog), SimRelicId.PaperPhrog },
            { typeof(ParryingShield), SimRelicId.ParryingShield },
            { typeof(Pear), SimRelicId.Pear },
            { typeof(Pendulum), SimRelicId.Pendulum },
            { typeof(PenNib), SimRelicId.PenNib },
            { typeof(Permafrost), SimRelicId.Permafrost },
            { typeof(PetrifiedToad), SimRelicId.PetrifiedToad },
            { typeof(PhialHolster), SimRelicId.PhialHolster },
            { typeof(PhilosophersStone), SimRelicId.PhilosophersStone },
            { typeof(PhylacteryUnbound), SimRelicId.PhylacteryUnbound },
            { typeof(Planisphere), SimRelicId.Planisphere },
            { typeof(Pocketwatch), SimRelicId.Pocketwatch },
            { typeof(PollinousCore), SimRelicId.PollinousCore },
            { typeof(Pomander), SimRelicId.Pomander },
            { typeof(PotionBelt), SimRelicId.PotionBelt },
            { typeof(PowerCell), SimRelicId.PowerCell },
            { typeof(PrayerWheel), SimRelicId.PrayerWheel },
            { typeof(PrecariousShears), SimRelicId.PrecariousShears },
            { typeof(PreciseScissors), SimRelicId.PreciseScissors },
            { typeof(PreservedFog), SimRelicId.PreservedFog },
            { typeof(PrismaticGem), SimRelicId.PrismaticGem },
            { typeof(PumpkinCandle), SimRelicId.PumpkinCandle },
            { typeof(PunchDagger), SimRelicId.PunchDagger },
            { typeof(RadiantPearl), SimRelicId.RadiantPearl },
            { typeof(RainbowRing), SimRelicId.RainbowRing },
            { typeof(RazorTooth), SimRelicId.RazorTooth },
            { typeof(RedMask), SimRelicId.RedMask },
            { typeof(RedSkull), SimRelicId.RedSkull },
            { typeof(Regalite), SimRelicId.Regalite },
            { typeof(RegalPillow), SimRelicId.RegalPillow },
            { typeof(ReptileTrinket), SimRelicId.ReptileTrinket },
            { typeof(RingingTriangle), SimRelicId.RingingTriangle },
            { typeof(RingOfTheDrake), SimRelicId.RingOfTheDrake },
            { typeof(RingOfTheSnake), SimRelicId.RingOfTheSnake },
            { typeof(RippleBasin), SimRelicId.RippleBasin },
            { typeof(RoyalPoison), SimRelicId.RoyalPoison },
            { typeof(RoyalStamp), SimRelicId.RoyalStamp },
            { typeof(RuinedHelmet), SimRelicId.RuinedHelmet },
            { typeof(RunicCapacitor), SimRelicId.RunicCapacitor },
            { typeof(RunicPyramid), SimRelicId.RunicPyramid },
            { typeof(Sai), SimRelicId.Sai },
            { typeof(SandCastle), SimRelicId.SandCastle },
            { typeof(ScreamingFlagon), SimRelicId.ScreamingFlagon },
            { typeof(ScrollBoxes), SimRelicId.ScrollBoxes },
            { typeof(SeaGlass), SimRelicId.SeaGlass },
            { typeof(SealOfGold), SimRelicId.SealOfGold },
            { typeof(SelfFormingClay), SimRelicId.SelfFormingClay },
            { typeof(SereTalon), SimRelicId.SereTalon },
            { typeof(Shovel), SimRelicId.Shovel },
            { typeof(Shuriken), SimRelicId.Shuriken },
            { typeof(SignetRing), SimRelicId.SignetRing },
            { typeof(SilkenTress), SimRelicId.SilkenTress },
            { typeof(SilverCrucible), SimRelicId.SilverCrucible },
            { typeof(SlingOfCourage), SimRelicId.SlingOfCourage },
            { typeof(SmallCapsule), SimRelicId.SmallCapsule },
            { typeof(SneckoEye), SimRelicId.SneckoEye },
            { typeof(SneckoSkull), SimRelicId.SneckoSkull },
            { typeof(Sozu), SimRelicId.Sozu },
            { typeof(SparklingRouge), SimRelicId.SparklingRouge },
            { typeof(SpikedGauntlets), SimRelicId.SpikedGauntlets },
            { typeof(StoneCalendar), SimRelicId.StoneCalendar },
            { typeof(StoneCracker), SimRelicId.StoneCracker },
            { typeof(StoneHumidifier), SimRelicId.StoneHumidifier },
            { typeof(Storybook), SimRelicId.Storybook },
            { typeof(Strawberry), SimRelicId.Strawberry },
            { typeof(StrikeDummy), SimRelicId.StrikeDummy },
            { typeof(SturdyClamp), SimRelicId.SturdyClamp },
            { typeof(SwordOfJade), SimRelicId.SwordOfJade },
            { typeof(SwordOfStone), SimRelicId.SwordOfStone },
            { typeof(SymbioticVirus), SimRelicId.SymbioticVirus },
            { typeof(TanxsWhistle), SimRelicId.TanxsWhistle },
            { typeof(TeaOfDiscourtesy), SimRelicId.TeaOfDiscourtesy },
            { typeof(TheAbacus), SimRelicId.TheAbacus },
            { typeof(TheBoot), SimRelicId.TheBoot },
            { typeof(TheCourier), SimRelicId.TheCourier },
            { typeof(ThrowingAxe), SimRelicId.ThrowingAxe },
            { typeof(Tingsha), SimRelicId.Tingsha },
            { typeof(TinyMailbox), SimRelicId.TinyMailbox },
            { typeof(ToastyMittens), SimRelicId.ToastyMittens },
            { typeof(Toolbox), SimRelicId.Toolbox },
            { typeof(TouchOfOrobas), SimRelicId.TouchOfOrobas },
            { typeof(ToughBandages), SimRelicId.ToughBandages },
            { typeof(ToxicEgg), SimRelicId.ToxicEgg },
            { typeof(ToyBox), SimRelicId.ToyBox },
            { typeof(TriBoomerang), SimRelicId.TriBoomerang },
            { typeof(TungstenRod), SimRelicId.TungstenRod },
            { typeof(TuningFork), SimRelicId.TuningFork },
            { typeof(TwistedFunnel), SimRelicId.TwistedFunnel },
            { typeof(UnceasingTop), SimRelicId.UnceasingTop },
            { typeof(UndyingSigil), SimRelicId.UndyingSigil },
            { typeof(UnsettlingLamp), SimRelicId.UnsettlingLamp },
            { typeof(Vajra), SimRelicId.Vajra },
            { typeof(Vambrace), SimRelicId.Vambrace },
            { typeof(VelvetChoker), SimRelicId.VelvetChoker },
            { typeof(VenerableTeaSet), SimRelicId.VenerableTeaSet },
            { typeof(VeryHotCocoa), SimRelicId.VeryHotCocoa },
            { typeof(VexingPuzzlebox), SimRelicId.VexingPuzzlebox },
            { typeof(VitruvianMinion), SimRelicId.VitruvianMinion },
            { typeof(WarHammer), SimRelicId.WarHammer },
            { typeof(WarPaint), SimRelicId.WarPaint },
            { typeof(Whetstone), SimRelicId.Whetstone },
            { typeof(WhisperingEarring), SimRelicId.WhisperingEarring },
            { typeof(WhiteBeastStatue), SimRelicId.WhiteBeastStatue },
            { typeof(WhiteStar), SimRelicId.WhiteStar },
            { typeof(WingCharm), SimRelicId.WingCharm },
            { typeof(WingedBoots), SimRelicId.WingedBoots },
            { typeof(WongoCustomerAppreciationBadge), SimRelicId.WongoCustomerAppreciationBadge },
            { typeof(WongosMysteryTicket), SimRelicId.WongosMysteryTicket },
            { typeof(YummyCookie), SimRelicId.YummyCookie },
        }.ToFrozenDictionary();

    /// <summary>Index i true ⇔ SimRelicId i overrides DisplayAmount or ShowCounter.</summary>
    private static readonly bool[] _hasCounter = BuildHasCounterTable();

    private static bool[] BuildHasCounterTable()
    {
        var table = new bool[SimRelicId.Count];
        foreach (KeyValuePair<Type, ushort> entry in _byType)
        {
            Type t = entry.Key;
            PropertyInfo displayAmount = t.GetProperty(nameof(RelicModel.DisplayAmount))
                ?? throw new InvalidOperationException($"SimRelicDb: {t.Name}.DisplayAmount not found.");
            PropertyInfo showCounter = t.GetProperty(nameof(RelicModel.ShowCounter))
                ?? throw new InvalidOperationException($"SimRelicDb: {t.Name}.ShowCounter not found.");

            bool overridesDisplayAmount = displayAmount.DeclaringType != typeof(RelicModel);
            bool overridesShowCounter = showCounter.DeclaringType != typeof(RelicModel);
            table[entry.Value] = overridesDisplayAmount || overridesShowCounter;
        }
        return table;
    }

    public static bool TryGetId(Type relicType, out ushort id) => _byType.TryGetValue(relicType, out id);

    public static ushort GetId(Type relicType)
    {
        if (_byType.TryGetValue(relicType, out ushort id))
            return id;

        throw new InvalidOperationException($"SimRelicDb: relic type '{relicType.FullName}' is not registered.");
    }

    public static bool HasCounter(ushort id) => _hasCounter[id];
}
